### PR TITLE
Added simple JSX widget test rig

### PR DESCRIPTION
**Pull request by michbil**

### CODE REVIEW

**Comment by AlexeyAnshakov** [comment]
@spirinvladimir , please review

**Comment by michbil** [comment]
Made simple hack to in jsx.js line 58 to wrap CommonJS module. So it working.

**Comment by michbil** [comment]
Also working on command line switch to enable testing for developers, not for production

**Comment by spirinvladimir** [comment]
nice hack

**Comment by AlexeyAnshakov** [comment]
@spirinvladimir, is it ready?

**Comment by michbil** [comment]
Alexey, please wait until i add command line switch for testing

**Comment by AlexeyAnshakov** [comment]
@spirinvladimir , I've added a new label (pull request: ready), please add this status asap it ready to go.

**Comment by michbil** [comment]
Have made all relevant changes, added command line for testing, @spirinvladimir any other notes?

**Comment by spirinvladimir** [comment]
pull request: ready

**Pull request merged**
